openapi: 3.0.0
info:
  title: Super Admin
  description: |-
    Primarily create Super admin in swasthx

    - add supder admin
        
    - add admin
        
    - update admin
        
    - search admin doctors
  version: 1.0.0
servers:
  - url: undefined://{{baseUrl}}
tags:
  - name: Add Admin
  - name: Add Super Admin
  - name: Delete Admin
  - name: Get All Admin
  - name: Update Admin Details
paths:
  /superAdmin/addAdmin:
    post:
      tags:
        - Add Admin
      summary: add admin
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                phoneNumber: 5555555555
                EntityID: AarogyaId
                email: AarogyaId@gmail.com
                name: AarogyaId super admin
                specialization: Cardiolgist
                registrationCouncil: string
                hospitalId: AarogyaId
                role: super admin
                permissions:
                  - Claim Insurance
                  - Analytics
                  - Insurance Payment
                  - Get Payer Info
                  - Request Document
                  - Payment
                  - Patient
                  - Queue
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /superAdmin/addSuperAdmin:
    post:
      tags:
        - Add Super Admin
      summary: add super admin
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                phoneNumber: 5555555555
                EntityID: AarogyaId
                email: AarogyaId@gmail.com
                name: AarogyaId super admin
                specialization: Cardiolgist
                registrationCouncil: string
                hospitalId: AarogyaId
                role: super admin
                permissions:
                  - Claim Insurance
                  - Analytics
                  - Insurance Payment
                  - Get Payer Info
                  - Request Document
                  - Payment
                  - Patient
                  - Queue
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /superAdmin/deleteAdminProfile:
    delete:
      tags:
        - Delete Admin
      summary: delete admin
      parameters:
        - name: targetAdminId
          in: query
          schema:
            type: string
          example: mnkj
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /superAdmin/searchAdmin:
    get:
      tags:
        - Get All Admin
      summary: search admin
      parameters:
        - name: addedBy
          in: query
          schema:
            type: string
          example: AarogyaId
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /superAdmin/updateAdminDetails:
    patch:
      tags:
        - Update Admin Details
      summary: udpate admin detaisl
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                keyName: name
                value: test admin 2
                doctorId: mnkj
                phoneNumber: 9999999999
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
